### ISSUE TITLE
Saving stamina

### ISSUE THREAD

**Issue by Bremaweb** [Bremaweb/adventuretest#13]
The stamina file needs to be saved at regular intervals instead of just at server shutdown. If there is a crash changes to a player's stamina will be lost.

**Comment by asl97** [comment]
what's is the point of stamina?
as far as i can tell, it isn't use at all.

also https://github.com/Bremaweb/adventuretest/commit/9cb663d488cb5f1cc7d5a7523356cba4b23f1e8b doesn't cleanly fix this.

**Comment by Bremaweb** [comment]
Line 47 of energy.lua is where stamina is applied to the energy adjustment. Stamina helps you use less energy when moving, regain energy faster when standing, sitting, or sleeping.
