### ISSUE TITLE
Seed 1456638851335458141 is problematic

### ISSUE THREAD

**Issue by hoodedice** [Bremaweb/adventuretest#3]
Player spawns over a huge abyss, and there are huge chucks cut off from the landscape. May be a problem in the mapgen code.

http://i.imgur.com/9pDeGx0.png
http://i.imgur.com/FR4Pe6w.png

**Comment by Bremaweb** [comment]
Did it crash at any point? That's what it does when it crashes during mapgen.

**Comment by hoodedice** [comment]
It crashed on initial first load with an out of memory error. I had about 200 MB of totally free RAM (Not cached), and about 500 MB of cached RAM.

Should I try loading the same seed again after deleting the world?

**Comment by hoodedice** [comment]
Fixed by https://github.com/minetest/minetest/issues/1527 probably.

**Comment by Bremaweb** [comment]
Switched mapgens so it shouldn't be an issue any longer.
