### ISSUE TITLE
error in hud function 

### ISSUE THREAD

**Issue by Baggypants** [Bremaweb/adventuretest#4]
I've tried to start some games with this but they fail

error from debug.txt
16:09:44: ERROR[main]: ServerError: caught (...)
16:09:44: ERROR[main]: stack traceback:
16:09:44: ERROR[main]:  [C]: in function 'hud_change'
16:09:44: ERROR[main]:  ...ggypants/.minetest/games/adventuretest/mods/hud/init.lua:247: in function 'update_hud'
16:09:44: ERROR[main]:  ...ggypants/.minetest/games/adventuretest/mods/hud/init.lua:357: in function <...ggypants/.minetest/games/adventuretest/mods/hud/init.lua:313>
16:09:44: ERROR[main]:  /usr/share/minetest/builtin/game/register.lua:341: in function </usr/share/minetest/builtin/game/register.lua:329>

I'm running minetest 0.4.12

**Comment by Sukender** [comment]
I just fixed it. See pull request #5 .

**Comment by ExcaliburZero** [comment]
Since pull request #5 has been merged, has this issue been fixed? If so, then it should be closed.
